import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { Transaction } from './entities/transaction.entity';

@Injectable()
export class PdfService {
  generateTransactionReport(transactions: Transaction[]) {
    const doc = new PDFDocument({ margin: 40 });
    
    // Calculate totals
    const income = transactions
      .filter(t => t.type === 'INCOME')
      .reduce((sum, t) => sum + Number(t.amount), 0);
    
    const expense = transactions
      .filter(t => t.type === 'EXPENSE')
      .reduce((sum, t) => sum + Number(t.amount), 0);
    
    const balance = income - expense;
    
    // Header
    doc.fontSize(24).font('Helvetica-Bold');
    doc.text('Transaction Report', 40, 50);
    
    // Date
    doc.fontSize(10).font('Helvetica');
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 40, 80);
    
    // Summary section
    doc.moveDown(2);
    doc.fontSize(16).font('Helvetica-Bold');
    doc.text('Summary', 40, doc.y);
    
    doc.moveDown(0.5);
    doc.fontSize(12).font('Helvetica');
    doc.text(`Total Income: $${income.toFixed(2)}`, 40, doc.y);
    doc.text(`Total Expense: $${expense.toFixed(2)}`, 40, doc.y);
    doc.text(`Balance: $${balance.toFixed(2)}`, 40, doc.y);
    
    // Transactions section
    doc.moveDown(2);
    doc.fontSize(16).font('Helvetica-Bold');
    doc.text(`All Transactions (${transactions.length})`, 40, doc.y);
    
    // Table header - adjusted column widths to fit page
    doc.moveDown(1);
    const tableTop = doc.y;
    const colWidths = [65, 55, 140, 70, 70, 75]; // Total: 475px (fits within ~512px available)
    const colPositions = [40];
    for (let i = 0; i < colWidths.length - 1; i++) {
      colPositions.push(colPositions[i] + colWidths[i]);
    }
    
    const tableWidth = colWidths.reduce((a, b) => a + b, 0);
    
    // Draw table header background
    doc.rect(40, tableTop - 5, tableWidth, 25).fill('#f0f0f0');
    
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#000000');
    doc.text('Date', colPositions[0] + 3, tableTop + 3, { width: colWidths[0] - 6 });
    doc.text('Type', colPositions[1] + 3, tableTop + 3, { width: colWidths[1] - 6 });
    doc.text('Description', colPositions[2] + 3, tableTop + 3, { width: colWidths[2] - 6 });
    doc.text('Category', colPositions[3] + 3, tableTop + 3, { width: colWidths[3] - 6 });
    doc.text('Source', colPositions[4] + 3, tableTop + 3, { width: colWidths[4] - 6 });
    doc.text('Amount', colPositions[5] + 3, tableTop + 3, { width: colWidths[5] - 6, align: 'right' });
    
    // Table rows
    let rowTop = tableTop + 25;
    let isEvenRow = true;
    
    transactions.forEach((transaction) => {
      // Check if we need a new page
      if (rowTop > 720) {
        doc.addPage();
        rowTop = 50;
      }
      
      // Alternating row background
      if (isEvenRow) {
        doc.rect(40, rowTop - 2, tableWidth, 18).fill('#f9f9f9');
      }
      
      doc.fontSize(8).font('Helvetica').fillColor('#000000');
      doc.text(
        new Date(transaction.date).toLocaleDateString(),
        colPositions[0] + 2,
        rowTop,
        { width: colWidths[0] - 4 }
      );
      doc.text(transaction.type, colPositions[1] + 2, rowTop, { width: colWidths[1] - 4 });
      doc.text(transaction.description, colPositions[2] + 2, rowTop, { 
        width: colWidths[2] - 4,
        ellipsis: true
      });
      doc.text(transaction.category?.name || 'N/A', colPositions[3] + 2, rowTop, { width: colWidths[3] - 4 });
      doc.text(transaction.source.replace('_', ' '), colPositions[4] + 2, rowTop, { width: colWidths[4] - 4 });
      
      const amountText = `$${Number(transaction.amount).toFixed(2)}`;
      const amountColor = transaction.type === 'INCOME' ? '#27ae60' : '#e74c3c';
      doc.fillColor(amountColor).text(amountText, colPositions[5] + 2, rowTop, { 
        width: colWidths[5] - 4, 
        align: 'right' 
      });
      doc.fillColor('#000000');
      
      rowTop += 18;
      isEvenRow = !isEvenRow;
    });
    
    // Footer
    doc.fontSize(8).font('Helvetica');
    doc.text(
      'Generated by Spend Tracker',
      40,
      doc.page.height - 50,
      { align: 'center', width: doc.page.width - 80 }
    );
    
    doc.end();
    return doc;
  }
}
